services:
  mini_postgres:
    container_name: mini_postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/db/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mini"]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - mini_network
  mini_api:
    container_name: mini_api
    restart: on-failure
    depends_on:
      - mini_postgres
    environment:
      DATABASE_URL: ${{ secrets.DB_DRIVER }}://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@mini_postgres/${{ secrets.DB_NAME }}
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mini_network

networks:
  mini_network:
    name: mini_network
 