name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-versions: [ '1.24.3' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go ${{matrix.go-versions}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-versions}}
      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:   
          working-directory: ./api
      - name: Testing
        run: cd ./api && go test -v ./...
      - name: Go back from ./api
        run: cd ..